//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.OrdersBill = new HashSet<OrdersBill>();
        }
    
        public int ID_bill { get; set; }
        public decimal PurchaseAmount { get; set; }
        public int Dentistry_ID { get; set; }
        public int Clients_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Dentistry Dentistry { get; set; }
        public virtual Doctors Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersBill> OrdersBill { get; set; }
    }
}
