//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Bill = new HashSet<Bill>();
            this.ClientDoctor = new HashSet<ClientDoctor>();
        }
    
        public int ID_doctors { get; set; }
        public string DoctorSurname { get; set; }
        public string DoctorName { get; set; }
        public string DoctorMiddlename { get; set; }
        public int TypeOfDoctor_ID { get; set; }
        public int loginpassword_ID { get; set; }
        public int Dentistry_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDoctor> ClientDoctor { get; set; }
        public virtual Dentistry Dentistry { get; set; }
        public virtual LoginPassword LoginPassword { get; set; }
        public virtual TypeOfDoctor TypeOfDoctor { get; set; }
    }
}
