//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentistryEntities1 : DbContext
    {
        public DentistryEntities1()
            : base("name=DentistryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<ClientDoctor> ClientDoctor { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Dentistry> Dentistry { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<LoginPassword> LoginPassword { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersBill> OrdersBill { get; set; }
        public virtual DbSet<OrdersMedicines> OrdersMedicines { get; set; }
        public virtual DbSet<OrdersService> OrdersService { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Servicess> Servicess { get; set; }
        public virtual DbSet<Statuss> Statuss { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockMedicines> StockMedicines { get; set; }
        public virtual DbSet<TypeOfDoctor> TypeOfDoctor { get; set; }
    }
}
