//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika5
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMedicines
    {
        public int ID_stockmedicines { get; set; }
        public int medicines_ID { get; set; }
        public int stock_ID { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
